### ISSUE TITLE
Public release checklist

### ISSUE THREAD

**Issue by Shnatsel** [Shnatsel/rust-audit#7]
- [x] A more robust way to locate Cargo.lock file in `auditable`
 - [x] Store dependencies in a format other than raw Cargo.lock; will likely involve `cargo-lock` crate for parsing it
 - [x] Create a pure-Rust recovery tool, based on https://github.com/RazrFalcon/cargo-bloat/issues/59 or libgoblin
 - [x] crates.io name acquisition and publishing
